### ISSUE TITLE
feat: kis9a navigation dockerlize

### ISSUE THREAD

**Issue by kis9a** [kis9a/navigation#4]
```
error /app/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /app/node_modules/gifsicle
Output:
⚠ spawn /app/node_modules/gifsicle/vendor/gifsicle ENOENT
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: not found


    at /app/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'web' failed to build : The command '/bin/sh -c yarn' returned a non-zero code: 1

```

**Comment by kis9a** [comment]
https://github.com/cyrilwanner/next-optimized-images/issues/12#issuecomment-378743176

**Comment by kis9a** [comment]
not working

**Comment by kis9a** [comment]
DockerでNode.jsアプリをイイ感じに保つ4つの方法 #docker
CL LAB
Docker

https://www.creationline.com/lab/29422

**Comment by kis9a** [comment]
docker image

node alpine  -> node slim

**Comment by kis9a** [comment]
````

navigation    | PNG support not compiled. Please install the libpng development package before building.

navigation    | JPEG support not compiled. Please install the libjpeg development package before building.

```

**Comment by kis9a** [comment]
can't fix

try to change image

node slim ->  node

**Comment by kis9a** [comment]
##### production
# FROM node:12-buster-slim as production

# RUN apt-get update -qq && \
#     apt-get install -y \
#     git \
#     curl \
#     make \
#     g++ \
#     autoconf \
#     automake \
#     libtool \
#     libpng-dev \
#     libjpeg-dev \
#     nasm \
#     libcurl4 \
#     dh-autoreconf && \
#     apt-get clean && \
#     curl -o- -L https://yarnpkg.com/install.sh | sh

# RUN cd /source && autoreconf -fiv && ./configure --prefix=/opt/mozjpeg && make install
# RUN yarn global add @vue/cli
# ENV PATH $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
# ENV CHOKIDAR_USEPOLLING=true

# RUN yarn
# CMD ["yarn", "run", "start"]

**Comment by kis9a** [comment]
##### production
FROM node:12-buster-slim as production

RUN apt-get update -qq && \
    apt-get install -y \
    git \
    curl \
    make \
    g++ \
    autoconf \
    automake \
    libtool \
    libpng-dev \
    libjpeg-dev \
    nasm \
    libcurl4 \
    dh-autoreconf && \
    apt-get clean && \
    curl -o- -L https://yarnpkg.com/install.sh | sh

RUN cd /source && autoreconf -fiv && ./configure --prefix=/opt/mozjpeg && make install
RUN yarn global add @vue/cli
ENV PATH $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
ENV CHOKIDAR_USEPOLLING=true

RUN yarn
CMD ["yarn", "run", "start"]

**Comment by kis9a** [comment]
### result

Stop to composite images in develop environment .
because can't resolve imagemin-webpack dependencies in docker node images container ,
and production image ubuntu:20.14 is too big for this project development .
but hosting CI pass this build and not expected dependencies bugs .
